### ISSUE TITLE
Support wezterm?

### ISSUE THREAD

**Issue by WindSoilder** [hardhackerlabs/themes#11]
Hi, sometimes I'm using wezterm too(it's faster than iterm2 and have multi-tab support)...

I think it's good to have wezterm support :-)

Here is a good example to define a wezterm theme: https://gist.github.com/theoriginalstove/89aa16316a756721816886398080dbd6

**Comment by SaitoWu** [comment]
Sorry mate, for the late reply. 🍻

All of us are not wezterm user, so we created a wezterm repo: https://github.com/hardhackerlabs/theme-wezterm 

If you don't mind,  you can create you own theme and send us a PR, That will be awesome. 🙏

color palette down below:  https://github.com/hardhackerlabs/themes#color-palette


<img width="551" alt="image" src="https://user-images.githubusercontent.com/348915/235972327-eb650a32-38ce-46ce-92a8-ba6d65fface7.png">
