### ISSUE TITLE
When will the HardHacker Darker theme be supported

### ISSUE THREAD

**Issue by sevenaper** [hardhackerlabs/themes#13]
When will the HardHacker Darker theme be supported like vscode?

**Comment by anson0370** [comment]
You mean all other tools or a specific one like JetBrains IDE?

**Comment by sevenaper** [comment]
> You mean all other tools or a specific one like JetBrains IDE?



> You mean all other tools or a specific one like JetBrains IDE?

the JetBrains IDE

**Comment by anson0370** [comment]
Done. It will take two business days for JetBrains marketplace to approve it. You should available to try it next week.

**Comment by sevenaper** [comment]
thanks a lot.
