### ISSUE TITLE
A light version HardHacker theme preview. What do you think?

### ISSUE THREAD

**Issue by anson0370** [hardhackerlabs/themes#14]
<img width="2672" alt="image" src="https://user-images.githubusercontent.com/283559/236596869-c3009c60-1312-41e3-be8d-1db80f1b7a4a.png">

It's a bit difficult to create a light theme that meets the WCAG AA standard and keep its uniqueness. To conform to the standard, all colors need to be saturated and brightness needs to be reduced. This makes all light themes look very similar.

**Comment by shenghui0779** [comment]
Add Light High Contrast ？

**Comment by anson0370** [comment]
> Add Light High Contrast ？

Once the color palette for the light version is finalized, I will create a high contrast version similar to the one in the dark version.

**Comment by anson0370** [comment]
@shenghui0779 Once version 0.2.1 is approved, you will be able to experience the light high contrast version.

**Comment by shenghui0779** [comment]
OK 👍
