### ISSUE TITLE
Port for Kitty terminal emulator

### ISSUE THREAD

**Issue by miropls** [hardhackerlabs/themes#16]
Hi, really like the theme and finally figured out that instead of waiting I'd make the port my self. So here is an initial version of the HardHacker theme for the Kitty terminal. Let me know if there's anything to be changed.

Repo is **[here](https://github.com/miropls/hardhacker-kitty)**.

**Comment by miropls** [comment]
My pleasure! And thank you guys for an excellent color scheme. Hits all the right spots for me!

I'll close the issue.

**Comment by anson0370** [comment]
I'm very glad that you like this theme. Your contribution and feedback is a great encouragement.
