### ISSUE TITLE
Inlay hint is unreadable

### ISSUE THREAD

**Issue by WindSoilder** [hardhackerlabs/themes#19]
Hi, I'm here again, after trying inlay hint feature from nightly neovim, I found that the hint text is unreadable

[![asciicast](https://asciinema.org/a/97Nhkwep2M6fXKescY60h6kxL.svg)](https://asciinema.org/a/97Nhkwep2M6fXKescY60h6kxL)

It'd be good if the color is readble to user

**Comment by anson0370** [comment]
非常感谢你的反馈，请 skoo 帮忙确认一下这个问题。

**Comment by anson0370** [comment]
Oops, mistake operation.

Thank you very much for your feedback. Please @skoowoo help confirm this issue.

**Comment by skoowoo** [comment]
I don't see what's unreadable about it ???  Explain that to me, please, thanks.

**Comment by WindSoilder** [comment]
Sure!  Take [OneDark](https://github.com/navarasu/onedark.nvim) theme as example, when I enable inlay hint, it shows the type of `x` variable clearly:
![图片](https://github.com/hardhackerlabs/themes/assets/22256154/3260dd57-8d43-4a67-8fcf-1c5f4b997321)
But in hardhacker theme, it doesn't show anything because of color I believe:
![图片](https://github.com/hardhackerlabs/themes/assets/22256154/9e608182-86ba-4898-b2f9-9d43bea38843)

`&str` here is something called virtual text, which is returned by language server, in case if you're interested, here is relative pr in neovim: https://github.com/neovim/neovim/pull/23984

**Comment by skoowoo** [comment]
Oh, I got it. Thank u, I will fix it.

**Comment by WindSoilder** [comment]
BTW, I've managed to set a comment color for inlay hint text.
```lua
local on_attach = function(client, bufnr)
  if client.server_capabilities.inlayHintProvider then
    vim.api.nvim_set_hl(0, "LspInlayHint", { fg = "#938aad" })
    nmap('<leader>ih', function() vim.lsp.inlay_hint(0, nil) end, "Toggle [I]nlay [H]int")
  end
end
```

I copy relative setting from a youtube channel and another plugin.
Sorry for that I'm not good at lua and vim plugin system, not really sure where should I put relative code.  Just hope it can help.

**Comment by WindSoilder** [comment]
Oh..my bad, just found I open the issue in a wrong repo.
