### ISSUE TITLE
Vscode 滚动条错误提示被遮盖

### ISSUE THREAD

**Issue by AlbertDCQ** [hardhackerlabs/themes#2]
下方图片的最右侧的两个红点是 Vscode 的两个错误提示，正常情况他们是一样高的。
当我用了这个主题后我发现滚动条会将这个错误提示遮住，希望可以滚动条可以透过错误提示
![image](https://user-images.githubusercontent.com/128760144/233015432-6ee2ae2e-d3b9-4a85-a534-b60f7a34e3d6.png)

这是 One Dark Pro 的效果
![image](https://user-images.githubusercontent.com/128760144/233016437-cf7f9f6b-b225-46a5-8113-52fb96375e6d.png)

**Comment by anson0370** [comment]
感谢指出，这确实有点问题。
已经调整了滚动条颜色，增加了透明度，稍晚等审核完成后直接在marketplace更新0.1.2版本即可。
如果还有问题或感觉可以更好，请重开这个issue。😜
