### ISSUE TITLE
Webstorm 2023.2.5 - Theme not working

### ISSUE THREAD

**Issue by TiagoSaAdvizr** [hardhackerlabs/themes#21]
Hello, 

I've updated hard hacker to the latest version and suddenly the darker theme does not work properly.

Screenshots: 

<img width="559" alt="Screenshot 2023-11-14 at 13 01 25" src="https://github.com/hardhackerlabs/themes/assets/33251659/98c86c70-af3a-4423-9886-ba4e98e2d9ae">

<img width="2504" alt="Screenshot 2023-11-14 at 13 02 28" src="https://github.com/hardhackerlabs/themes/assets/33251659/e23016c6-0fa6-4631-9c43-843f10745249">

Thank you

**Comment by anson0370** [comment]
I installed WebStorm and HardHacker theme, unfortunately, I wasn't able to reproduce the issue.😥
Looks like that the UI of the IDE is functioning correctly, but the editor schema is not.
Could you check the value under Settings -> Editor -> Color Schema? If it's correct, my suggestion would be to try uninstalling and reinstalling.🥲

**Comment by olfway** [comment]
I had same issue with IntelliJ Idea 2023.2.5 after 0.2.5 theme release
Settings -> Editor -> Color Schema was reseted to "Light", so I had to go there and manually change it back to Hard Hacker
After that it works perfectly

**Comment by TiagoSaAdvizr** [comment]
It worked! 
Thank you @olfway
