### ISSUE TITLE
Not compatible with the version of your running IDE (PyCharm 2024.1 EAP)

### ISSUE THREAD

**Issue by nomas** [hardhackerlabs/themes#22]
As a dedicated and frequent user of this tool, I find it indispensable for my software development tasks. The functionality and efficiency it offers have become integral to my workflow, and the current lack of compatibility significantly impacts my productivity.Thank you for your attention to this matter, and I look forward to the release of a compatible update soon.

Best regards

**Comment by anson0370** [comment]
I just released version 0.2.6, removing the 'until-build' restriction. It should be available once IntelliJ approves it. However, I haven't thoroughly tested compatibility, so if there are any issues, please feel free to provide feedback.

**Comment by anson0370** [comment]
I will close this issue. Feel free to reopen it if necessary.
